version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: foody_vegetarian
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - foody_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1G



  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - foody_net
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: foody_vegetarian

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - foody_net
    depends_on:
      - backend

  nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx
      ports:
        - "1234:80"
      depends_on:
        - frontend
        - backend
      networks:
        - foody_net
      volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
  # frontend-builder:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - frontend_build:/app/dist

  # mysql:
  #   container_name: db
  #   image: mysql:8.0
  #   ports:
  #     - 3308:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #   volumes:
  #     - ./init_db:/docker-entrypoint-initdb.d/:ro
  #     - ./mysql_data/:/var/lib/mysql

  # nginx:
  #     build:
  #       context: ./nginx
  #       dockerfile: Dockerfile
  #     ports:
  #       - "8002:80"
  #     depends_on:
  #       - frontend-builder
  #     volumes:
  #       - frontend_build:/usr/share/nginx/html
  #     networks:
  #       - foody_net

volumes:
  db_data:


networks:
  foody_net:
